name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.19.0
        - name: Install
          run: npm install
        - name: Test
          env:
            BROWSERSTACK_USER : ${{ secrets.BROWSERSTACK_USER }}
            BROWSERSTACK_KEY : ${{ secrets.BROWSERSTACK_KEY }}
          run: npx wdio run config/wdio.android.bs.conf.js -spec test/specs/android/add-note-screen.spec.js
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
